// frontend/src/views/DashboardView.vue
<template>
  <div class="content-area">
    <div class="page-header-flex">
      <h2 class="page-title">Dashboards Analíticos</h2>
    </div>

    <div class="dashboard-kpis">
      <div class="kpi-card">
        <h3>Total de Álbumes</h3>
        <div class="kpi-value">{{ stats?.total_albums ?? 0 }}</div>
        <p class="kpi-desc">Colecciones indexadas en la base de datos.</p>
      </div>
      <div class="kpi-card">
        <h3>Total de Canciones</h3>
        <div class="kpi-value">{{ stats?.total_songs ?? 0 }}</div>
        <p class="kpi-desc">Letras disponibles para análisis.</p>
      </div>
      <div class="kpi-card">
        <h3>Agregadas Recientemente</h3>
        <div class="kpi-value status-ok">+{{ stats?.recently_added ?? 0 }}</div>
        <p class="kpi-desc">En los últimos 30 días.</p>
      </div>
      <div class="kpi-card">
        <h3>Canciones con Letra</h3>
        <div class="kpi-value">{{ stats?.songs_with_lyrics ?? 0 }}</div>
        <p class="kpi-desc">De {{ stats?.total_songs ?? 0 }} totales.</p>
      </div>
      <div class="kpi-card">
        <h3>Promedio de Caracteres</h3>
        <div class="kpi-value">~{{ avgLyricsChars }}</div>
        <p class="kpi-desc">Longitud promedio de letra.</p>
      </div>
    </div>

    <div class="dashboard-charts">
      <div class="chart-container">
        <Bar :data="albumChartData" :options="albumChartOptions" />
      </div>
      <div class="chart-container">
        <Doughnut :data="clasificacionChartData" :options="doughnutChartOptions" />
      </div>
    </div>

    <div class="dashboard-charts">
      <div class="chart-container">
        <Line :data="yearLineChartData" :options="yearLineChartOptions" />
      </div>
      <div class="chart-container">
        <Bar :data="oovChartData" :options="oovChartOptions" />
      </div>
    </div>

    <div class="dashboard-charts dashboard-charts--single">
      <div class="chart-container chart-container--tall">
        <PolarArea :data="indigenaChartData" :options="polarChartOptions" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement,
  LineElement,
  PointElement,
  RadialLinearScale,
} from 'chart.js';
import { Bar, Doughnut, Line, PolarArea } from 'vue-chartjs';
import { apiService } from '@/services/api';
import type { Stats } from '@/types';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement,
  LineElement,
  PointElement,
  RadialLinearScale
);

const stats = ref<Stats | null>(null);
const loading = ref(true);

onMounted(async () => {
  try {
    stats.value = await apiService.getStats();
  } catch (e) {
    console.error('Error loading stats:', e);
  } finally {
    loading.value = false;
  }
});

const avgLyricsChars = computed(() => {
  const val = stats.value?.avg_lyrics_length ?? 0;
  return val > 0 ? Math.round(val).toLocaleString() : '0';
});

// ── Album Bar Chart ──────────────────────────────────────────
const albumChartData = computed(() => {
  const top = stats.value?.top_albums ?? [];
  return {
    labels: top.map((a) => (a.album.length > 20 ? a.album.substring(0, 17) + '...' : a.album)),
    datasets: [
      {
        label: 'Cantidad de Canciones',
        data: top.map((a) => a.count),
        backgroundColor: 'rgba(117, 20, 40, 0.7)',
        borderColor: 'rgba(117, 20, 40, 1)',
        borderWidth: 1,
      },
    ],
  };
});

const albumChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  animation: { duration: 1000, easing: 'easeOutQuart' as const },
  plugins: {
    legend: { display: false },
    title: {
      display: true,
      text: 'Distribución de Canciones por Álbum',
      font: { size: 14, weight: 'bold' as const },
      padding: { bottom: 20 },
    },
  },
  scales: {
    y: { beginAtZero: true, grid: { color: '#f1f5f9' } },
    x: { grid: { display: false } },
  },
};

// ── Clasificacion Doughnut ────────────────────────────────────
const clasificacionChartData = computed(() => {
  const map = stats.value?.songs_by_clasificacion ?? {};
  const labels: Record<string, string> = {
    ESPAÑOL_ESTANDAR: 'Español Estándar',
    ESPAÑOL_REGIONAL: 'Español Regional',
    LENGUA_INDIGENA: 'Lengua Indígena',
  };
  return {
    labels:
      Object.keys(map).length > 0
        ? Object.keys(map).map((k) => labels[k] ?? k)
        : ['Español Estándar', 'Español Regional', 'Lengua Indígena'],
    datasets: [
      {
        data: Object.values(map).length > 0 ? Object.values(map) : [35, 10, 40],
        backgroundColor: ['#c5a46c', '#60a5fa', '#751428'],
        hoverOffset: 20,
        borderWidth: 0,
      },
    ],
  };
});

const doughnutChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  animation: { duration: 1200, easing: 'easeInOutQuart' as const },
  cutout: '60%',
  plugins: {
    legend: {
      position: 'right' as const,
      labels: { usePointStyle: true, padding: 20, font: { size: 12 } },
    },
    title: {
      display: true,
      text: 'Clasificación Temática',
      font: { size: 14, weight: 'bold' as const },
      padding: { bottom: 20 },
    },
  },
};

// ── Year Line Chart ──────────────────────────────────────────
const yearLineChartData = computed(() => {
  const byYear = stats.value?.songs_by_year ?? {};
  const sortedYears = Object.keys(byYear).sort();
  return {
    labels: sortedYears,
    datasets: [
      {
        label: 'Canciones',
        data: sortedYears.map((y) => byYear[y]),
        borderColor: '#751428',
        backgroundColor: 'rgba(117, 20, 40, 0.1)',
        fill: true,
        tension: 0.4,
        pointRadius: 4,
        pointBackgroundColor: '#751428',
      },
    ],
  };
});

const yearLineChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  animation: { duration: 1200, easing: 'easeInOutQuart' as const },
  plugins: {
    legend: { display: false },
    title: {
      display: true,
      text: 'Canciones por Año',
      font: { size: 14, weight: 'bold' as const },
      padding: { bottom: 20 },
    },
  },
  scales: {
    y: { beginAtZero: true, grid: { color: '#f1f5f9' } },
    x: { grid: { display: false } },
  },
};

// ── OOV Level Bar Chart ────────────────────────────────────────
const oovChartData = computed(() => {
  const map = stats.value?.songs_by_oov_level ?? {};
  const labels: Record<string, string> = {
    BAJA: 'BAJA (<5%)',
    MEDIA: 'MEDIA (5-18%)',
    ALTA: 'ALTA (>18%)',
  };
  return {
    labels:
      Object.keys(map).length > 0
        ? Object.keys(map).map((k) => labels[k] ?? k)
        : ['BAJA (<5%)', 'MEDIA (5-18%)', 'ALTA (>18%)'],
    datasets: [
      {
        label: 'Nivel OOV',
        data: Object.values(map).length > 0 ? Object.values(map) : [10, 25, 5],
        backgroundColor: ['#34d399', '#fbbf24', '#f87171'],
        borderWidth: 0,
      },
    ],
  };
});

const oovChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  indexAxis: 'y' as const,
  animation: { duration: 1200, easing: 'easeInOutQuart' as const },
  plugins: {
    legend: { display: false },
    title: {
      display: true,
      text: 'Nivel de OOV por Canción',
      font: { size: 14, weight: 'bold' as const },
      padding: { bottom: 20 },
    },
  },
  scales: {
    x: { beginAtZero: true, grid: { color: '#f1f5f9' } },
    y: { grid: { display: false } },
  },
};

// ── Indigena Polar Chart ───────────────────────────────────────
const indigenaChartData = computed(() => {
  const map = stats.value?.songs_by_indigena ?? {};
  return {
    labels:
      Object.keys(map).length > 0
        ? Object.keys(map).map((k) =>
            k === 'CON_INDIGENA' ? 'Con Palabra Indígena' : 'Sin Palabra Indígena'
          )
        : ['Con Palabra Indígena', 'Sin Palabra Indígena'],
    datasets: [
      {
        data: Object.values(map).length > 0 ? Object.values(map) : [8, 42],
        backgroundColor: ['#c5a46c', '#751428'],
        borderWidth: 0,
      },
    ],
  };
});

const polarChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  animation: { duration: 1200, easing: 'easeInOutQuart' as const },
  plugins: {
    legend: {
      position: 'right' as const,
      labels: { usePointStyle: true, padding: 20, font: { size: 12 } },
    },
    title: {
      display: true,
      text: 'Presencia de Palabra Indígena',
      font: { size: 14, weight: 'bold' as const },
      padding: { bottom: 20 },
    },
  },
  scales: {
    r: {
      ticks: { display: false },
      grid: { color: '#e2e8f0' },
    },
  },
};
</script>

<style scoped>
.dashboard-charts--single {
  grid-template-columns: 1fr;
  max-width: 600px;
}
</style>

// frontend/src/components/DashboardView.jsx
import React, { useEffect, useState } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement,
} from 'chart.js';
import { Bar, Pie } from 'react-chartjs-2';
import { apiService } from '../services/api';

// Registrar los módulos de chart.js que vamos a usar
ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend, ArcElement);

export const DashboardView = () => {
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    setLoading(true);
    apiService
      .getStats()
      .then((data) => {
        setStats(data);
        setLoading(false);
      })
      .catch((err) => {
        console.error('Error loading stats:', err);
        setError(err.message);
        setLoading(false);
      });
  }, []);

  const isMobile = window.innerWidth < 768;

  if (loading) {
    return (
      <div className="content-area">
        <div className="loading-state">
          <div className="spinner"></div>
          <p>Cargando métricas...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="content-area">
        <div className="page-header-flex">
          <h2 className="page-title">Dashboards Analíticos</h2>
        </div>
        <div className="auth-error">Error al cargar las métricas: {error}</div>
      </div>
    );
  }

  // Prepare chart data from real stats
  const topAlbums = stats?.top_albums || [];
  const songsByClasificacion = stats?.songs_by_clasificacion || {};

  // Bar chart data - Songs per Album (top 10)
  const barChartData = {
    labels: topAlbums.map((a) =>
      a.album.length > 20 ? a.album.substring(0, 17) + '...' : a.album
    ),
    datasets: [
      {
        label: 'Cantidad de Canciones',
        data: topAlbums.map((a) => a.count),
        backgroundColor: 'rgba(117, 20, 40, 0.7)',
        borderColor: 'rgba(117, 20, 40, 1)',
        borderWidth: 1,
      },
    ],
  };

  const barChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'top',
        display: !isMobile,
      },
      title: {
        display: true,
        text: 'Distribución de Canciones por Álbum',
        font: { size: isMobile ? 14 : 16, weight: 'bold' },
        padding: { bottom: 20 },
      },
    },
    scales: {
      y: {
        beginAtZero: true,
        grid: { color: '#f1f5f9' },
      },
      x: {
        grid: { display: false },
      },
    },
  };

  // Pie chart data - Songs by Clasificacion
  const clasificacionLabels =
    Object.keys(songsByClasificacion).length > 0
      ? Object.keys(songsByClasificacion).map((key) => {
          const labels = {
            ESPAÑOL_ESTANDAR: 'Español Estándar',
            ESPAÑOL_REGIONAL: 'Español Regional',
            LENGUA_INDIGENA: 'Lengua Indígena',
          };
          return labels[key] || key;
        })
      : ['Alegría', 'Melancolía', 'Infantil', 'Naturaleza', 'Otros'];

  const clasificacionValues =
    Object.values(songsByClasificacion).length > 0
      ? Object.values(songsByClasificacion)
      : [35, 10, 40, 10, 5];

  const pieChartData = {
    labels: clasificacionLabels,
    datasets: [
      {
        label: 'Proyección de Sentimientos',
        data: clasificacionValues,
        backgroundColor: [
          '#c5a46c', // Dorado
          '#60a5fa', // Azul
          '#751428', // Guinda
          '#34d399', // Verde
          '#a78bfa', // Morado
        ],
        hoverOffset: 20,
        borderWidth: 0,
      },
    ],
  };

  const pieChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: isMobile ? 'bottom' : 'right',
        labels: {
          usePointStyle: true,
          padding: 20,
          font: { size: 12 },
        },
      },
      title: {
        display: true,
        text: 'Clasificación Temática',
        font: { size: isMobile ? 14 : 16, weight: 'bold' },
        padding: { bottom: 20 },
      },
    },
  };

  return (
    <div className="content-area">
      <div className="page-header-flex">
        <h2 className="page-title">Dashboards Analíticos</h2>
      </div>

      {/* Tarjetas de Métricas Rápidas (KPIs) */}
      <div className="dashboard-kpis">
        <div className="kpi-card">
          <h3>Total de Álbumes</h3>
          <div className="kpi-value">{stats?.total_albums || 0}</div>
          <p className="kpi-desc">Colecciones indexadas en la base de datos.</p>
        </div>

        <div className="kpi-card">
          <h3>Total de Canciones</h3>
          <div className="kpi-value">{stats?.total_songs || 0}</div>
          <p className="kpi-desc">Letras disponibles para análisis.</p>
        </div>

        <div className="kpi-card">
          <h3>Agregadas Recientemente</h3>
          <div className="kpi-value status-ok">+{stats?.recently_added || 0}</div>
          <p className="kpi-desc">En los últimos 30 días.</p>
        </div>
      </div>

      {/* Contenedores de Gráficos */}
      <div className="dashboard-charts">
        <div className="chart-container">
          <Bar data={barChartData} options={barChartOptions} />
        </div>

        <div className="chart-container">
          <Pie data={pieChartData} options={pieChartOptions} />
        </div>
      </div>
    </div>
  );
};
